name: Dotnet Build and Test

on:
  push:
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.305'
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Start Azurite
        shell: bash
        run: |
          docker run -d \
            -p 10000:10000 \
            -p 10001:10001 \
            -p 10002:10002 \
            --name azurite-ci \
            mcr.microsoft.com/azure-storage/azurite

          echo "Waiting for Azurite..."
          for i in {1..20}; do
            if curl -s http://localhost:10000/ > /dev/null; then
              echo "Azurite is ready!"
              break
            fi
            sleep 1
          done
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Run test
        run: dotnet test

      - name: Stop Azurite
        if: always()
        run: docker rm -f azurite-ci
